# AUTO-GENERATED by synthigy.codegen from example.xsql — DO NOT EDIT.
# sourceHash: 910e896bca103bfb54a133eb4343b16801d89b206311de3eb76cd14bc641edad
# Regenerate: python3 -m synthigy.codegen gen example.xsql
"""Typed Synthigy operations — ONE async engine under both surfaces.
Async apps: synthigy.aconnect(...) once at startup, then the *Async
classes / *_async batch functions — awaitable reads, native-async
watch handles (async with / async for). Async writes need no
codegen: `await synthigy.aclient().stack(entity, data)` takes the
same typed *Input dicts emitted below.

Blocking scripts/notebooks: synthigy.connect(...) and the plain
classes — same engine behind a one-thread blocking facade.

Data keys are snake_case verbatim — Python native IS server native;
no casing transform is applied anywhere.
"""
from __future__ import annotations

from typing import Any, Literal, TypedDict, overload  # noqa: F401

try:
    from typing import NotRequired  # Python >= 3.11
except ImportError:  # pragma: no cover
    from typing_extensions import NotRequired  # type: ignore

import synthigy
from synthigy import SynthigyError
from synthigy import ops as _ops



def _batch_result(result: dict, op: str) -> Any:
    """Per-member unwrap: ok → data (get → record|None, else → list);
    error → a SynthigyError VALUE (the batch itself never raises)."""
    if not result.get("ok"):
        err = result.get("error") or {}
        return SynthigyError(err.get("message", "operation failed"),
                             err.get("code", "OPERATION_FAILED"),
                             err.get("details"))
    data = result.get("data")
    if op == "get":
        return data
    return data if data is not None else []


_SRC_MOVIE_LIST = (
    '@search list\n'
    'movie (release_year > ?since:int=1980, limit ?limit:int=20, offset ?offset:int=0, order by release_year desc)\n'
    '  xid\n'
    '  title (ilike ?q:string="%")\n'
    '  release_year\n'
    '  _count\n'
    '    ratings:movie_ratings\n'
    '    actors:actors\n'
    '  _agg\n'
    '    ratings:movie_ratings\n'
    '      value: avg\n'
    '  ->genres\n'
    '    xid\n'
    '    name'
)

_SRC_MOVIE_DETAIL = (
    '@get detail\n'
    'movie (xid = ?xid:string)\n'
    '  xid\n'
    '  title\n'
    '  release_year\n'
    '  ->movie_ratings\n'
    '    xid\n'
    '    value\n'
    '    review\n'
    '    ->created_by\n'
    '      xid\n'
    '      name\n'
    '  ->genres\n'
    '    xid\n'
    '    name\n'
    '  ->actors\n'
    '    xid\n'
    '    name\n'
    '    birth_year'
)

_SRC_MOVIE_COUNT = (
    'SELECT count(*) AS total FROM {movie}\n'
    'WHERE release_year > ?since:int=1995 AND title ILIKE ?q:string="%"'
)

_SRC_DASHBOARD_STATS = (
    '-- One CTE per entity, not scalar subqueries: RLS guards are injected per\n'
    '-- CTE scope, so each aggregate is scoped to what the caller may read.\n'
    'WITH m  AS (SELECT count(*) AS n FROM {movie}),\n'
    '     r  AS (SELECT count(*) AS n, avg({user_rating.value}) AS avg_value FROM {user_rating}),\n'
    '     ma AS (SELECT count(*) AS n FROM {movie_actor})\n'
    'SELECT m.n          AS total_movies,\n'
    '       r.n          AS total_ratings,\n'
    '       r.avg_value  AS avg_rating,\n'
    '       ma.n         AS total_actors\n'
    'FROM m, r, ma'
)


MovieListParams = TypedDict("MovieListParams", {
    "since": NotRequired[int],
    "limit": NotRequired[int],
    "offset": NotRequired[int],
    "q": NotRequired[str],
})


MovieListRowGenres = TypedDict("MovieListRowGenres", {
    "xid": str,
    "name": str | None,
})


MovieListRow = TypedDict("MovieListRow", {
    "xid": str,
    "title": str | None,
    "release_year": int | None,
    "_count": NotRequired[dict[str, int]],
    "_agg": NotRequired[dict[str, Any]],
    "genres": NotRequired[list[MovieListRowGenres]],
})


MovieDetailParams = TypedDict("MovieDetailParams", {
    "xid": str,
})


MovieDetailRowMovieRatingsCreatedBy = TypedDict("MovieDetailRowMovieRatingsCreatedBy", {
    "xid": str,
    "name": str | None,
})


MovieDetailRowMovieRatings = TypedDict("MovieDetailRowMovieRatings", {
    "xid": str,
    "value": float,
    "review": str | None,
    "created_by": NotRequired[MovieDetailRowMovieRatingsCreatedBy],
})


MovieDetailRowGenres = TypedDict("MovieDetailRowGenres", {
    "xid": str,
    "name": str | None,
})


MovieDetailRowActors = TypedDict("MovieDetailRowActors", {
    "xid": str,
    "name": str | None,
    "birth_year": int | None,
})


MovieDetailRow = TypedDict("MovieDetailRow", {
    "xid": str,
    "title": str | None,
    "release_year": int | None,
    "movie_ratings": NotRequired[list[MovieDetailRowMovieRatings]],
    "genres": NotRequired[list[MovieDetailRowGenres]],
    "actors": NotRequired[list[MovieDetailRowActors]],
})


MovieCountParams = TypedDict("MovieCountParams", {
    "since": NotRequired[int],
    "q": NotRequired[str],
})


MovieCountRow = TypedDict("MovieCountRow", {
    "total": int,
})


DashboardStatsRow = TypedDict("DashboardStatsRow", {
    "total_movies": int,
    "total_ratings": int,
    "avg_rating": float | None,
    "total_actors": int,
})


OverviewBatchParams = TypedDict("OverviewBatchParams", {
    "since": NotRequired[int],
    "limit": NotRequired[int],
    "offset": NotRequired[int],
    "q": NotRequired[str],
})


class Dashboard:
    """Typed operations for XSQL namespace 'dashboard'."""

    @staticmethod
    def stats(**opts: Any) -> list[DashboardStatsRow]:
        """Dashboard headline numbers."""
        return synthigy.sql_template(_SRC_DASHBOARD_STATS, {}, **opts)

    @staticmethod
    def watch_stats(**opts: Any) -> Any:
        """Live stats — notify-then-refetch watch over the same op. Returns the watch handle (.ready() / .events() / .close())."""
        return synthigy.watch_sql_template(_SRC_DASHBOARD_STATS, {}, entities=['movie', 'user_rating', 'movie_actor'], **opts)


class DashboardAsync:
    """Async twins for XSQL namespace 'dashboard' — run on
    the module-default AsyncClient (synthigy.aconnect). Reads
    are awaitable; watch_* return native-async handles
    (`async with` / `async for`)."""

    @staticmethod
    async def stats(**opts: Any) -> list[DashboardStatsRow]:
        """Dashboard headline numbers."""
        return await synthigy.aclient().sql_template(_SRC_DASHBOARD_STATS, {}, **opts)

    @staticmethod
    def watch_stats(**opts: Any) -> Any:
        """Live stats — native-async watch (`async with ... as w`, `async for ev in w`; derived query/added|changed|removed events)."""
        return synthigy.aclient().watch_sql_template(_SRC_DASHBOARD_STATS, {}, entities=['movie', 'user_rating', 'movie_actor'], **opts)


class Movie:
    """Typed operations for XSQL namespace 'movie'."""

    @staticmethod
    def list(params: MovieListParams | None = None, **opts: Any) -> list[MovieListRow]:
        """Movies newest-first with rating/actor counts, average rating and genres.
        Filter by title with ?q (ilike) and minimum release year with ?since.
        """
        return synthigy.query(_SRC_MOVIE_LIST, dict(params or {}), op='search', **opts)

    @staticmethod
    def watch_list(params: MovieListParams | None = None, **opts: Any) -> Any:
        """Live list — notify-then-refetch watch over the same op. Returns the watch handle (.ready() / .events() / .close())."""
        return synthigy.watch_query_xsql(_SRC_MOVIE_LIST, dict(params or {}), entity='movie', **opts)

    @staticmethod
    def detail(params: MovieDetailParams, **opts: Any) -> MovieDetailRow | None:
        """One movie by xid — ratings with reviewer, plus genres and cast."""
        return synthigy.query(_SRC_MOVIE_DETAIL, dict(params), op='get', **opts)

    @staticmethod
    def watch_detail(params: MovieDetailParams, **opts: Any) -> Any:
        """Live detail — notify-then-refetch watch over the same op. Returns the watch handle (.ready() / .events() / .close())."""
        return synthigy.watch_query_xsql(_SRC_MOVIE_DETAIL, dict(params), entity='movie', **opts)

    @staticmethod
    def count(params: MovieCountParams | None = None, **opts: Any) -> list[MovieCountRow]:
        """Movie count under the same ?since / ?q filters the list uses."""
        return synthigy.sql_template(_SRC_MOVIE_COUNT, dict(params or {}), **opts)


class MovieAsync:
    """Async twins for XSQL namespace 'movie' — run on
    the module-default AsyncClient (synthigy.aconnect). Reads
    are awaitable; watch_* return native-async handles
    (`async with` / `async for`)."""

    @staticmethod
    async def list(params: MovieListParams | None = None, **opts: Any) -> list[MovieListRow]:
        """Movies newest-first with rating/actor counts, average rating and genres.
        Filter by title with ?q (ilike) and minimum release year with ?since.
        """
        return await synthigy.aclient().query(_SRC_MOVIE_LIST, dict(params or {}), op='search', **opts)

    @staticmethod
    def watch_list(params: MovieListParams | None = None, **opts: Any) -> Any:
        """Live list — native-async watch (`async with ... as w`, `async for ev in w`; derived query/added|changed|removed events)."""
        return synthigy.aclient().watch_query_xsql(_SRC_MOVIE_LIST, dict(params or {}), entity='movie', **opts)

    @staticmethod
    async def detail(params: MovieDetailParams, **opts: Any) -> MovieDetailRow | None:
        """One movie by xid — ratings with reviewer, plus genres and cast."""
        return await synthigy.aclient().query(_SRC_MOVIE_DETAIL, dict(params), op='get', **opts)

    @staticmethod
    def watch_detail(params: MovieDetailParams, **opts: Any) -> Any:
        """Live detail — native-async watch (`async with ... as w`, `async for ev in w`; derived query/added|changed|removed events)."""
        return synthigy.aclient().watch_query_xsql(_SRC_MOVIE_DETAIL, dict(params), entity='movie', **opts)

    @staticmethod
    async def count(params: MovieCountParams | None = None, **opts: Any) -> list[MovieCountRow]:
        """Movie count under the same ?since / ?q filters the list uses."""
        return await synthigy.aclient().sql_template(_SRC_MOVIE_COUNT, dict(params or {}), **opts)


def overview(params: OverviewBatchParams | None = None, **opts: Any) -> dict[str, Any]:
    """Batch: list + stats — ONE wire request; results keyed by member name. A failed member's value is a SynthigyError instance (not raised)."""
    _p = dict(params or {})
    _operations = [
        _ops.query(_SRC_MOVIE_LIST, _p, op='search'),
        _ops.sql_template(_SRC_DASHBOARD_STATS, _p),
    ]
    _results = synthigy.exec_(_operations, **opts)
    return {
        "list": _batch_result(_results[0], 'search'),
        "stats": _batch_result(_results[1], 'sql-template'),
    }


async def overview_async(params: OverviewBatchParams | None = None, **opts: Any) -> dict[str, Any]:
    """Batch: list + stats — ONE wire request; results keyed by member name. A failed member's value is a SynthigyError instance (not raised)."""
    _p = dict(params or {})
    _operations = [
        _ops.query(_SRC_MOVIE_LIST, _p, op='search'),
        _ops.sql_template(_SRC_DASHBOARD_STATS, _p),
    ]
    _results = await synthigy.aclient().exec_(_operations, **opts)
    return {
        "list": _batch_result(_results[0], 'search'),
        "stats": _batch_result(_results[1], 'sql-template'),
    }


# A write relation accepts a LINK to an existing record ({"xid": ...})
# or a full nested write.
_Link = TypedDict("_Link", {"xid": str})


MovieInput = TypedDict("MovieInput", {
    "xid": NotRequired[str],
    "release_year": NotRequired[int | None],
    "title": NotRequired[str | None],
    "genres": "NotRequired[list[_Link | MovieGenreInput]]",
    "movie_ratings": "NotRequired[list[_Link | UserRatingInput]]",
    "actors": "NotRequired[list[_Link | MovieActorInput]]",
})


MovieWriteResult = TypedDict("MovieWriteResult", {
    "xid": str,
    "release_year": NotRequired[int | None],
    "title": NotRequired[str | None],
    "genres": NotRequired[list[dict[str, Any]]],
    "movie_ratings": NotRequired[list[dict[str, Any]]],
    "actors": NotRequired[list[dict[str, Any]]],
})


MovieActorInput = TypedDict("MovieActorInput", {
    "xid": NotRequired[str],
    "name": NotRequired[str | None],
    "nationality": NotRequired[str | None],
    "birth_year": NotRequired[int | None],
    "movies": "NotRequired[list[_Link | MovieInput]]",
})


MovieActorWriteResult = TypedDict("MovieActorWriteResult", {
    "xid": str,
    "name": NotRequired[str | None],
    "nationality": NotRequired[str | None],
    "birth_year": NotRequired[int | None],
    "movies": NotRequired[list[dict[str, Any]]],
})


MovieGenreInput = TypedDict("MovieGenreInput", {
    "xid": NotRequired[str],
    "name": NotRequired[str | None],
    "movies": "NotRequired[list[_Link | MovieInput]]",
})


MovieGenreWriteResult = TypedDict("MovieGenreWriteResult", {
    "xid": str,
    "name": NotRequired[str | None],
    "movies": NotRequired[list[dict[str, Any]]],
})


UserInput = TypedDict("UserInput", {
    "xid": NotRequired[str],
    "priority": NotRequired[int | None],
    "settings": NotRequired[Any | None],
    "name": NotRequired[str | None],
    "avatar": NotRequired[Any | None],
    "type": NotRequired[Literal['PERSON', 'SERVICE', 'ROBOT'] | None],
    "modified_on": NotRequired[str | None],
    "password": NotRequired[str | None],
    "active": NotRequired[bool | None],
    "created_on": NotRequired[str | None],
    "notification_preferences": "NotRequired[list[dict[str, Any]]]",
    "owner": "NotRequired[dict[str, Any]]",
    "user_profile": "NotRequired[dict[str, Any]]",
    "loggers": "NotRequired[list[dict[str, Any]]]",
    "person_info": "NotRequired[dict[str, Any]]",
    "company_section": "NotRequired[dict[str, Any]]",
    "can_read_folder": "NotRequired[list[dict[str, Any]]]",
    "sessions": "NotRequired[list[dict[str, Any]]]",
    "notifications": "NotRequired[list[dict[str, Any]]]",
    "chat_groups": "NotRequired[list[dict[str, Any]]]",
    "external_identities": "NotRequired[list[dict[str, Any]]]",
    "created_by": "NotRequired[_Link | UserInput]",
    "authorized_client": "NotRequired[dict[str, Any]]",
    "approval_records": "NotRequired[list[dict[str, Any]]]",
    "robot_repo": "NotRequired[dict[str, Any]]",
    "approvals": "NotRequired[list[dict[str, Any]]]",
    "public_profile": "NotRequired[dict[str, Any]]",
    "installations": "NotRequired[list[dict[str, Any]]]",
    "owned_datasets": "NotRequired[list[dict[str, Any]]]",
    "can_write_folder": "NotRequired[list[dict[str, Any]]]",
    "quick_filters": "NotRequired[list[dict[str, Any]]]",
    "projects": "NotRequired[list[dict[str, Any]]]",
    "modified_by": "NotRequired[_Link | UserInput]",
    "can_delete_folder": "NotRequired[list[dict[str, Any]]]",
    "roles": "NotRequired[list[dict[str, Any]]]",
    "groups": "NotRequired[list[dict[str, Any]]]",
})


UserWriteResult = TypedDict("UserWriteResult", {
    "xid": str,
    "priority": NotRequired[int | None],
    "settings": NotRequired[Any | None],
    "name": NotRequired[str | None],
    "avatar": NotRequired[Any | None],
    "type": NotRequired[Literal['PERSON', 'SERVICE', 'ROBOT'] | None],
    "modified_on": NotRequired[str | None],
    "password": NotRequired[str | None],
    "active": NotRequired[bool | None],
    "created_on": NotRequired[str | None],
    "notification_preferences": NotRequired[list[dict[str, Any]]],
    "owner": NotRequired[dict[str, Any]],
    "user_profile": NotRequired[dict[str, Any]],
    "loggers": NotRequired[list[dict[str, Any]]],
    "person_info": NotRequired[dict[str, Any]],
    "company_section": NotRequired[dict[str, Any]],
    "can_read_folder": NotRequired[list[dict[str, Any]]],
    "sessions": NotRequired[list[dict[str, Any]]],
    "notifications": NotRequired[list[dict[str, Any]]],
    "chat_groups": NotRequired[list[dict[str, Any]]],
    "external_identities": NotRequired[list[dict[str, Any]]],
    "created_by": NotRequired[dict[str, Any]],
    "authorized_client": NotRequired[dict[str, Any]],
    "approval_records": NotRequired[list[dict[str, Any]]],
    "robot_repo": NotRequired[dict[str, Any]],
    "approvals": NotRequired[list[dict[str, Any]]],
    "public_profile": NotRequired[dict[str, Any]],
    "installations": NotRequired[list[dict[str, Any]]],
    "owned_datasets": NotRequired[list[dict[str, Any]]],
    "can_write_folder": NotRequired[list[dict[str, Any]]],
    "quick_filters": NotRequired[list[dict[str, Any]]],
    "projects": NotRequired[list[dict[str, Any]]],
    "modified_by": NotRequired[dict[str, Any]],
    "can_delete_folder": NotRequired[list[dict[str, Any]]],
    "roles": NotRequired[list[dict[str, Any]]],
    "groups": NotRequired[list[dict[str, Any]]],
})


UserRatingInput = TypedDict("UserRatingInput", {
    "xid": NotRequired[str],
    "value": float,
    "review": NotRequired[str | None],
    "modified_on": NotRequired[str | None],
    "created_on": NotRequired[str | None],
    "modified_by": "NotRequired[_Link | UserInput]",
    "user": "NotRequired[dict[str, Any]]",
    "movie": "NotRequired[_Link | MovieInput]",
    "created_by": "NotRequired[_Link | UserInput]",
})


UserRatingWriteResult = TypedDict("UserRatingWriteResult", {
    "xid": str,
    "value": NotRequired[float | None],
    "review": NotRequired[str | None],
    "modified_on": NotRequired[str | None],
    "created_on": NotRequired[str | None],
    "modified_by": NotRequired[dict[str, Any]],
    "user": NotRequired[dict[str, Any]],
    "movie": NotRequired[dict[str, Any]],
    "created_by": NotRequired[dict[str, Any]],
})


@overload
def sync_movie(data: MovieInput, **opts: Any) -> MovieWriteResult: ...
@overload
def sync_movie(data: list[MovieInput], **opts: Any) -> list[MovieWriteResult]: ...
def sync_movie(data, **opts):
    """Upsert movie record(s) — REPLACES relation link-sets."""
    return synthigy.sync('movie', data, **opts)


@overload
def stack_movie(data: MovieInput, **opts: Any) -> MovieWriteResult: ...
@overload
def stack_movie(data: list[MovieInput], **opts: Any) -> list[MovieWriteResult]: ...
def stack_movie(data, **opts):
    """Additive write to movie — relation links are ADDED, never removed."""
    return synthigy.stack('movie', data, **opts)


def delete_movie(xid: str, **opts: Any) -> Any:
    """Soft-delete one movie record by xid."""
    return synthigy.delete('movie', {"xid": xid}, **opts)


@overload
def sync_movie_actor(data: MovieActorInput, **opts: Any) -> MovieActorWriteResult: ...
@overload
def sync_movie_actor(data: list[MovieActorInput], **opts: Any) -> list[MovieActorWriteResult]: ...
def sync_movie_actor(data, **opts):
    """Upsert movie_actor record(s) — REPLACES relation link-sets."""
    return synthigy.sync('movie_actor', data, **opts)


@overload
def stack_movie_actor(data: MovieActorInput, **opts: Any) -> MovieActorWriteResult: ...
@overload
def stack_movie_actor(data: list[MovieActorInput], **opts: Any) -> list[MovieActorWriteResult]: ...
def stack_movie_actor(data, **opts):
    """Additive write to movie_actor — relation links are ADDED, never removed."""
    return synthigy.stack('movie_actor', data, **opts)


def delete_movie_actor(xid: str, **opts: Any) -> Any:
    """Soft-delete one movie_actor record by xid."""
    return synthigy.delete('movie_actor', {"xid": xid}, **opts)


@overload
def sync_movie_genre(data: MovieGenreInput, **opts: Any) -> MovieGenreWriteResult: ...
@overload
def sync_movie_genre(data: list[MovieGenreInput], **opts: Any) -> list[MovieGenreWriteResult]: ...
def sync_movie_genre(data, **opts):
    """Upsert movie_genre record(s) — REPLACES relation link-sets."""
    return synthigy.sync('movie_genre', data, **opts)


@overload
def stack_movie_genre(data: MovieGenreInput, **opts: Any) -> MovieGenreWriteResult: ...
@overload
def stack_movie_genre(data: list[MovieGenreInput], **opts: Any) -> list[MovieGenreWriteResult]: ...
def stack_movie_genre(data, **opts):
    """Additive write to movie_genre — relation links are ADDED, never removed."""
    return synthigy.stack('movie_genre', data, **opts)


def delete_movie_genre(xid: str, **opts: Any) -> Any:
    """Soft-delete one movie_genre record by xid."""
    return synthigy.delete('movie_genre', {"xid": xid}, **opts)


@overload
def sync_user(data: UserInput, **opts: Any) -> UserWriteResult: ...
@overload
def sync_user(data: list[UserInput], **opts: Any) -> list[UserWriteResult]: ...
def sync_user(data, **opts):
    """Upsert user record(s) — REPLACES relation link-sets."""
    return synthigy.sync('user', data, **opts)


@overload
def stack_user(data: UserInput, **opts: Any) -> UserWriteResult: ...
@overload
def stack_user(data: list[UserInput], **opts: Any) -> list[UserWriteResult]: ...
def stack_user(data, **opts):
    """Additive write to user — relation links are ADDED, never removed."""
    return synthigy.stack('user', data, **opts)


def delete_user(xid: str, **opts: Any) -> Any:
    """Soft-delete one user record by xid."""
    return synthigy.delete('user', {"xid": xid}, **opts)


@overload
def sync_user_rating(data: UserRatingInput, **opts: Any) -> UserRatingWriteResult: ...
@overload
def sync_user_rating(data: list[UserRatingInput], **opts: Any) -> list[UserRatingWriteResult]: ...
def sync_user_rating(data, **opts):
    """Upsert user_rating record(s) — REPLACES relation link-sets."""
    return synthigy.sync('user_rating', data, **opts)


@overload
def stack_user_rating(data: UserRatingInput, **opts: Any) -> UserRatingWriteResult: ...
@overload
def stack_user_rating(data: list[UserRatingInput], **opts: Any) -> list[UserRatingWriteResult]: ...
def stack_user_rating(data, **opts):
    """Additive write to user_rating — relation links are ADDED, never removed."""
    return synthigy.stack('user_rating', data, **opts)


def delete_user_rating(xid: str, **opts: Any) -> Any:
    """Soft-delete one user_rating record by xid."""
    return synthigy.delete('user_rating', {"xid": xid}, **opts)
